# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "titipat achakulvisut"
title:              "titipat personal page"
description:        "minimal personal page for titipat achakulvisut. feel free to check out project, small blogs and basic information about me"


# URL
url:                http://titipata.github.io
baseurl:            http://titipata.github.io
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "about"
    href:           "/about"
  - name:           "blog"
    href:           "/blog"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
